test
Ozzyben/maze-game pull request #2
Opened 2020-04-03 15:51 UTC by GRANT225

2020-04-03 16:18 UTC, jrome5 commented
"System.NullReferenceException: Object reference not set to an instance of an object
  at Packages.Rider.Editor.UnitTesting.CallbackInitializer..cctor () [0x00001] in C:\Users\GRANT\Documents\maze-game-master\maze-game-master\mazegame\Library\PackageCache\com.unity.ide.rider@1.1.4\Rider\Editor\UnitTesting\CallbackInitializer.cs:13 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])"

There seems to be an issue when i clone this branch. Not sure what seems to try and link to but it seems to want to grab an address from your documents.

2020-04-03 17:08 UTC, GRANT225 commented
To view maze-game.zip, sign in<https://heriotwatt-my.sharepoint.com/personal/gms4_hw_ac_uk/_layouts/15/acceptinvite.aspx?invitation=%7BACF08DF8%2DDA3F%2D4EEB%2DBB0F%2DF231AD424E22%7D&listId=ac5621c8%2D3bd1%2D4637%2Dbd78%2D1e739f1c5e19&itemId=ec66c34a%2Deb32%2D472e%2Db9b4%2D1d237a1da18f> or create an account.
________________________________

Founded in 1821, Heriot-Watt is a leader in ideas and solutions. With campuses and students across the entire globe we span the world, delivering innovation and educational excellence in business, engineering, design and the physical, social and life sciences. This email is generated from the Heriot-Watt University Group, which includes:

  1.  Heriot-Watt University, a Scottish charity registered under number SC000278
  2.  Heriot- Watt Services Limited (Oriam), Scotland's national performance centre for sport. Heriot-Watt Services Limited is a private limited company registered is Scotland with registered number SC271030 and registered office at Research & Enterprise Services Heriot-Watt University, Riccarton, Edinburgh, EH14 4AS.

The contents (including any attachments) are confidential. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system.

2020-04-03 17:08 UTC, GRANT225 commented
Swanson, Grant M has shared a OneDrive for Business file with you. To view it, click the link below.
<https://heriotwatt-my.sharepoint.com/personal/gms4_hw_ac_uk/Documents/Attachments/maze-game.zip>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://heriotwatt-my.sharepoint.com/personal/gms4_hw_ac_uk/Documents/Attachments/maze-game.zip>
maze-game.zip<https://heriotwatt-my.sharepoint.com/personal/gms4_hw_ac_uk/Documents/Attachments/maze-game.zip>


________________________________
From: jrome5 <notifications@github.com>
Sent: 03 April 2020 17:19
To: Ozzyben/maze-game <maze-game@noreply.github.com>
Cc: Swanson, Grant M <gms4@hw.ac.uk>; Author <author@noreply.github.com>
Subject: Re: [Ozzyben/maze-game] test (#2)


"System.NullReferenceException: Object reference not set to an instance of an object
at Packages.Rider.Editor.UnitTesting.CallbackInitializer..cctor () [0x00001] in C:\Users\GRANT\Documents\maze-game-master\maze-game-master\mazegame\Library\PackageCache\com.unity.ide.rider@1.1.4\Rider\Editor\UnitTesting\CallbackInitializer.cs:13
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])"

There seems to be an issue when i clone this branch. Not sure what seems to try and link to but it seems to want to grab an address from your documents.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Ozzyben/maze-game/pull/2#issuecomment-608532563>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALSBE54W7ZIQR27FY2FNGNLRKYD7XANCNFSM4L4GFBWQ>.

________________________________

Founded in 1821, Heriot-Watt is a leader in ideas and solutions. With campuses and students across the entire globe we span the world, delivering innovation and educational excellence in business, engineering, design and the physical, social and life sciences. This email is generated from the Heriot-Watt University Group, which includes:

  1.  Heriot-Watt University, a Scottish charity registered under number SC000278
  2.  Heriot- Watt Services Limited (Oriam), Scotland's national performance centre for sport. Heriot-Watt Services Limited is a private limited company registered is Scotland with registered number SC271030 and registered office at Research & Enterprise Services Heriot-Watt University, Riccarton, Edinburgh, EH14 4AS.

The contents (including any attachments) are confidential. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system.

2020-04-04 12:18 UTC, jrome5 requested changes

2020-04-04 12:18 UTC, jrome5 commented on mazegame/Assets/Scripts/Menu/MenuText.cs
> +        this.transform.localScale += new Vector3(0.4f, 0.4f, 0.4f);
please assign this to a private class variable. Such as `private Vector3 text_scaling = Vector3(0.4f, 0.4f, 0.4f);`

2020-04-04 12:18 UTC, jrome5 commented on mazegame/Assets/Scripts/Menu/MenuText.cs
> +        this.transform.localScale -= new Vector3(0.4f, 0.4f, 0.4f);
same here. add class variable. `this.transform.localScale -= text_scaling

2020-04-04 12:18 UTC, jrome5 commented on mazegame/Assets/Scripts/Maze/TextEditor.cs
> +    string key3_found = "You found a third key! ... *click*... Sounds like a door has opened";
From what i can tell, these class member variables are never used anywhere else apart from in one instance inside the class. 
1. Move these to `Start` function
2. Make them type `var`
3. Avoid the use of numbers in variable names. Please rename to `first_key_found`

2020-04-05 17:40 UTC, merged